"""add_search_indexes

Revision ID: 34849fb626ca
Revises: acd60a378924
Create Date: 2026-06-03 22:19:10.158522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34849fb626ca'
down_revision: Union[str, Sequence[str], None] = 'acd60a378924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_legislative_documents_bill_type'), 'legislative_documents', ['bill_type'], unique=False)
    op.create_index(op.f('ix_legislative_documents_last_action_date'), 'legislative_documents', ['last_action_date'], unique=False)
    op.create_index(op.f('ix_legislative_documents_policy_area'), 'legislative_documents', ['policy_area'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislative_documents_policy_area'), table_name='legislative_documents')
    op.drop_index(op.f('ix_legislative_documents_last_action_date'), table_name='legislative_documents')
    op.drop_index(op.f('ix_legislative_documents_bill_type'), table_name='legislative_documents')
    # ### end Alembic commands ###
