"""add_bill_actions_table

Revision ID: 95e22ebe8425
Revises: 34849fb626ca
Create Date: 2026-06-04 10:47:20.750377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e22ebe8425'
down_revision: Union[str, Sequence[str], None] = '34849fb626ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('action_code', sa.String(length=50), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('source_system_code', sa.Integer(), nullable=True),
    sa.Column('source_system_name', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['legislative_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_actions_action_date'), 'bill_actions', ['action_date'], unique=False)
    op.create_index(op.f('ix_bill_actions_document_id'), 'bill_actions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_actions_document_id'), table_name='bill_actions')
    op.drop_index(op.f('ix_bill_actions_action_date'), table_name='bill_actions')
    op.drop_table('bill_actions')
    # ### end Alembic commands ###
