"""Add checkpoint fields to sync_logs

Revision ID: acd60a378924
Revises: ed9a30f9ed08
Create Date: 2026-06-03 16:50:41.724732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd60a378924'
down_revision: Union[str, Sequence[str], None] = 'ed9a30f9ed08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_logs', sa.Column('congress', sa.Integer(), nullable=True))
    op.add_column('sync_logs', sa.Column('total_bills_discovered', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sync_logs', sa.Column('last_processed_bill', sa.String(length=100), nullable=True))
    op.add_column('sync_logs', sa.Column('last_processed_page', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sync_logs', sa.Column('active_bills_stored', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sync_logs', sa.Column('inactive_bills_skipped', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sync_logs', sa.Column('api_requests_made', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sync_logs', sa.Column('started_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('sync_logs', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'updated_at')
    op.drop_column('sync_logs', 'started_at')
    op.drop_column('sync_logs', 'api_requests_made')
    op.drop_column('sync_logs', 'inactive_bills_skipped')
    op.drop_column('sync_logs', 'active_bills_stored')
    op.drop_column('sync_logs', 'last_processed_page')
    op.drop_column('sync_logs', 'last_processed_bill')
    op.drop_column('sync_logs', 'total_bills_discovered')
    op.drop_column('sync_logs', 'congress')
    # ### end Alembic commands ###
