"""Initial schema

Revision ID: ed9a30f9ed08
Revises: 
Create Date: 2026-06-03 15:03:01.259394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed9a30f9ed08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_subjects_subject_name'), 'animal_subjects', ['subject_name'], unique=True)
    op.create_table('legislative_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('bill_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('introduced_date', sa.Date(), nullable=True),
    sa.Column('origin_chamber', sa.String(length=50), nullable=True),
    sa.Column('policy_area', sa.String(length=100), nullable=True),
    sa.Column('last_action_date', sa.Date(), nullable=True),
    sa.Column('last_action_text', sa.String(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('update_date_incl_text', sa.DateTime(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('api_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislative_documents_source_id'), 'legislative_documents', ['source_id'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_subjects',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['legislative_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_subjects')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_legislative_documents_source_id'), table_name='legislative_documents')
    op.drop_table('legislative_documents')
    op.drop_index(op.f('ix_animal_subjects_subject_name'), table_name='animal_subjects')
    op.drop_table('animal_subjects')
    # ### end Alembic commands ###
